# MODULE_NAME = "FreeGPT"
# MODULE_CMD  = ".fg"
# MODULE_DESC = "Бесплатный ChatGPT без API. Команды: .fg .fgs .fgimg .fgchat .fgclear .fginfo"

import asyncio
import json as _json
import aiohttp
import random
import urllib.parse

from telethon import events
from bot_client import client
from premium_emoji import pe, by_line
from utils import html
from config import LOADING

# ---- Настройки ----
_MODEL_LABEL    = "ChatGPT"
_IMG_LABEL      = "Flux"
_fg_chat_active = {}
_fg_chat_history = {}
_fg_system      = "Ты умный и полезный ИИ-ассистент. Отвечай чётко и по делу. Используй HTML-форматирование где уместно."
_BLACKBOX_TAG   = "Generated by BLACKBOX.AI"

# Очистка: каждые 5 сгенерённых фото в чате — удаляем пачкой
_IMG_CLEAN_EVERY = 5
_fg_img_msgs: dict = {}   # {chat_id: [msg_id, ...]}

_POLLI_URL = "https://text.pollinations.ai/openai"


def _clean(text: str) -> str:
    return (text or "").split(_BLACKBOX_TAG)[0].strip()


def _answer_text(question: str, answer: str, chat: bool) -> str:
    prefix = "💬 " if chat else ""
    return (
        f'<tg-emoji emoji-id="5818813162815753343">👨‍💻</tg-emoji> <b>{prefix}Вопрос:</b> {html(question)}\n\n'
        f'<tg-emoji emoji-id="5372981976804366741">🤖</tg-emoji> <b>Ответ:</b>\n{answer}\n\n'
        f'<tg-emoji emoji-id="5424753383741346604">🖥</tg-emoji> <b>Модель:</b> <code>{_MODEL_LABEL}</code>\n\n'
        + by_line()
    )


def _build_messages(chat_id: int, question: str) -> list:
    if _fg_chat_active.get(chat_id):
        history = _fg_chat_history.setdefault(chat_id, [{"role": "system", "content": _fg_system}])
        history.append({"role": "user", "content": question})
        return list(history)
    return [
        {"role": "system", "content": _fg_system},
        {"role": "user",   "content": question},
    ]


def _save_reply(chat_id: int, answer: str):
    if _fg_chat_active.get(chat_id):
        hist = _fg_chat_history.setdefault(chat_id, [{"role": "system", "content": _fg_system}])
        hist.append({"role": "assistant", "content": answer})
        if len(hist) > 21:
            del hist[1]


async def _polli_chat(messages: list) -> str:
    payload = {"model": "openai", "messages": messages}
    timeout = aiohttp.ClientTimeout(total=90)
    async with aiohttp.ClientSession(timeout=timeout) as s:
        async with s.post(_POLLI_URL, json=payload) as r:
            r.raise_for_status()
            data = await r.json()
            return (data["choices"][0]["message"].get("content") or "").strip()


async def _g4f_fallback(messages: list) -> str:
    from g4f.client import Client as G4F
    def _req():
        return G4F().chat.completions.create(model="gpt-4o", messages=messages, stream=False)
    resp = await asyncio.get_event_loop().run_in_executor(None, _req)
    return (resp.choices[0].message.content or "").strip()


async def _ask(messages: list) -> str:
    try:
        return _clean(await _polli_chat(messages))
    except Exception as e1:
        try:
            return _clean(await _g4f_fallback(messages))
        except Exception as e2:
            raise RuntimeError(f"polli: {e1} | g4f: {e2}")


async def _track_img(chat_id: int, msg_id: int):
    """Каждые N сгенерённых фото — пачкой удаляются."""
    lst = _fg_img_msgs.setdefault(chat_id, [])
    lst.append(msg_id)
    if len(lst) >= _IMG_CLEAN_EVERY:
        try:
            await client.delete_messages(chat_id, lst)
        except Exception:
            pass
        _fg_img_msgs[chat_id] = []


@client.on(events.NewMessage(pattern=r"^\.fg\s+(.+)", outgoing=True))
async def cmd_fg(event):
    query = event.pattern_match.group(1).strip()
    await event.edit(LOADING, parse_mode="html")
    messages = _build_messages(event.chat_id, query)
    try:
        answer = await _ask(messages)
        _save_reply(event.chat_id, answer)
        await event.edit(_answer_text(query, answer, _fg_chat_active.get(event.chat_id, False)), parse_mode="html")
    except Exception as e:
        await event.edit(f"❌ <b>Ошибка GPT:</b>\n<code>{html(str(e)[:300])}</code>", parse_mode="html")


@client.on(events.NewMessage(pattern=r"^\.fgs\s+(.+)", outgoing=True))
async def cmd_fgs(event):
    query = event.pattern_match.group(1).strip()
    messages = _build_messages(event.chat_id, query)
    await event.edit(f'<b>Запрос:</b> {html(query)}\n\n<code>▍</code>', parse_mode="html")

    payload = {"model": "openai", "messages": messages, "stream": True}
    collected = ""
    last_edit = 0.0
    try:
        timeout = aiohttp.ClientTimeout(total=120)
        async with aiohttp.ClientSession(timeout=timeout) as s:
            async with s.post(_POLLI_URL, json=payload) as r:
                r.raise_for_status()
                async for raw in r.content:
                    line = raw.decode("utf-8", "ignore").strip()
                    if not line.startswith("data:"):
                        continue
                    data = line[5:].strip()
                    if data == "[DONE]":
                        break
                    if not data:
                        continue
                    try:
                        delta = _json.loads(data)["choices"][0]["delta"].get("content") or ""
                    except Exception:
                        continue
                    if not delta:
                        continue
                    collected += delta
                    now = asyncio.get_event_loop().time()
                    if now - last_edit > 0.8:
                        last_edit = now
                        try:
                            await event.edit(f'<b>Запрос:</b> {html(query)}\n\n{html(collected)}▍', parse_mode="html")
                        except Exception:
                            pass

        if not collected:
            collected = await _ask(messages)

        final = _clean(collected)
        _save_reply(event.chat_id, final)
        await event.edit(_answer_text(query, final, _fg_chat_active.get(event.chat_id, False)), parse_mode="html")
    except Exception as e:
        await event.edit(f"❌ <b>Ошибка:</b> <code>{html(str(e)[:300])}</code>", parse_mode="html")


@client.on(events.NewMessage(pattern=r"^\.fgimg\s+(.+)", outgoing=True))
async def cmd_fgimg(event):
    prompt = event.pattern_match.group(1).strip()
    await event.edit(f'<tg-emoji emoji-id="5334675996714999970">🔄</tg-emoji> <b>Генерация...</b>', parse_mode="html")

    try:
        seed = random.randint(1, 1000000)
        safe_q = urllib.parse.quote(prompt)
        img_url = (
            f"https://image.pollinations.ai/prompt/{safe_q}"
            f"?width=1024&height=1024&model=flux&seed={seed}&nologo=true"
        )

        try:
            sent = await client.send_file(
                event.chat_id,
                img_url,
                caption=f'<tg-emoji emoji-id="5375074927252621134">🖼</tg-emoji> <b>Промпт:</b> <code>{html(prompt)}</code>\n\n' + by_line(),
                parse_mode="html"
            )
            await event.delete()
            await _track_img(event.chat_id, sent.id)
        except Exception:
            await event.edit(
                f'<tg-emoji emoji-id="5375074927252621134">🖼</tg-emoji> <b>Изображение готово:</b>\n'
                f'🔗 <a href="{img_url}">Открыть оригинал</a>\n\n' + by_line(),
                parse_mode="html", link_preview=True
            )
            await _track_img(event.chat_id, event.id)

    except Exception as e:
        await event.edit(f"❌ <b>Ошибка:</b>\n<code>{html(str(e)[:200])}</code>", parse_mode="html")


@client.on(events.NewMessage(pattern=r"^\.fgchat$", outgoing=True))
async def cmd_fgchat(event):
    cid = event.chat_id
    _fg_chat_active[cid] = not _fg_chat_active.get(cid, False)
    state = "ВКЛ" if _fg_chat_active[cid] else "ВЫКЛ"
    await event.edit(f"🗣 <b>Режим диалога:</b> <code>{state}</code>")


@client.on(events.NewMessage(pattern=r"^\.fgclear$", outgoing=True))
async def cmd_fgclear(event):
    _fg_chat_history[event.chat_id] = [{"role": "system", "content": _fg_system}]
    await event.edit("🗑 <b>История очищена.</b>")


@client.on(events.NewMessage(pattern=r"^\.fginfo$", outgoing=True))
async def cmd_fginfo(event):
    await event.edit(
        f"👨‍💻 <b>FreeGPT Info</b>\n\n"
        f"Текст: <code>{_MODEL_LABEL}</code>\n"
        f"Фото: <code>{_IMG_LABEL}</code>\n"
        f"Диалог: <code>{'Да' if _fg_chat_active.get(event.chat_id) else 'Нет'}</code>\n\n"
        f"Используйте <code>.fg</code> для запросов.",
        parse_mode="html"
    )


_binary_handlers = [cmd_fg, cmd_fgs, cmd_fgimg, cmd_fgchat, cmd_fgclear, cmd_fginfo]
